fragment Draft on AppDraft {
  id
  tag
  userAddress
  lastUpdated
  contentProtocol
  json
}

query applicationDrafts($chainId: Int!) {
  AppDraft(where: { chainId: { _eq: $chainId } }) {
    ...Draft
  }
}

query applicationDraft($id: String!) {
  AppDraft_by_pk(id: $id) {
    ...Draft
  }
}

query applicationDraftsByUser($userAddress: String!, $chainId: Int!) {
  AppDraft(
    where: { userAddress: { _eq: $userAddress }, chainId: { _eq: $chainId } }
  ) {
    ...Draft
  }
}
