fragment Vote on GGApplicationVote {
  id
  createdAt
  amount
  feedback
}

fragment Application on GGApplication {
  id
  registrar
  application
  validApplication
  amountReviewed
  postedBy
  lastUpdated
  totalVoted
  votes {
    ...Vote
  }
}

query getApplicationRound($id: String!) {
  GGApplicationRound_by_pk(id: $id) {
    id
    createdAt
    votesParams_id
    choicesParams_id
    postedBy
    rubric
    validRubric
    applications {
      ...Application
    }
  }
}
