export const TAG = {
  APPLICATION_POST: 'GG_APPDRAFT_SUBMIT',
  APPLICATION_EDIT: 'GG_APPDRAFT_EDIT',
  APPLICATION_COMMENT: 'GG_APPDRAFT_COMMENT',
  APPLICATION_APPROVE: 'GG_APPDRAFT_APPROVE',
  APPLICATION_VOTE: 'GG_APPLICATION_VOTE',
};

export const CURRENT_ROUND = 'GG_23';

export const GG_MD_POINTER = 6665n;
