export const TAG = {
  APPLICATION_POST: 'GG_APPDRAFT_SUBMIT',
  APPLICATION_EDIT: 'GG_APPDRAFT_EDIT',
  APPLICATION_COMMENT: 'GG_APPDRAFT_COMMENT',
  APPLICATION_APPROVE: 'GG_APPDRAFT_APPROVE',
};

export const CURRENT_ROUND = 'GG_23';
